//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AniChan8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int admin_id { get; set; }
        public string name { get; set; }
        public string role_ { get; set; }
        public string user_name_ { get; set; }
        public string password_ { get; set; }
    }
}
