//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AniChan8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmark
    {
        public int bm_id { get; set; }
        public Nullable<int> user_id_ { get; set; }
        public Nullable<int> anime_id { get; set; }
    
        public virtual Anime Anime { get; set; }
        public virtual User User { get; set; }
    }
}
