//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AniChan8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public int trxn_id { get; set; }
        public Nullable<int> user_id_ { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
        public Nullable<double> amount { get; set; }
        public string payment_method { get; set; }
    
        public virtual User User { get; set; }
    }
}
